import { Operation, Trader } from "./types"

export const topTraders: Trader[] = [
  {
    id: "trader1",
    name: "Alex Morgan",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Crypto specialist with 7+ years of experience",
    winRate: 87,
    followers: 12453,
    totalTrades: 1245,
    isActive: true,
  },
  {
    id: "trader2",
    name: "Sarah Chen",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Forex expert focusing on major currency pairs",
    winRate: 82,
    followers: 8932,
    totalTrades: 2134,
    isActive: true,
  },
  {
    id: "trader3",
    name: "Michael Johnson",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Options trader specializing in tech stocks",
    winRate: 79,
    followers: 7621,
    totalTrades: 1876,
    isActive: false,
  },
  {
    id: "trader4",
    name: "David Wilson",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Futures and commodities specialist",
    winRate: 75,
    followers: 6543,
    totalTrades: 1543,
    isActive: true,
  },
  {
    id: "trader5",
    name: "Emma Roberts",
    avatar: "/placeholder.svg?height=40&width=40",
    bio: "Stock market analyst and day trader",
    winRate: 81,
    followers: 9876,
    totalTrades: 2345,
    isActive: true,
  },
]

export const liveOperations: Operation[] = [
  {
    id: "op1",
    trader: {
      id: "trader1",
      name: "Alex Morgan",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date().toISOString(),
    market: "crypto",
    type: "BUY",
    asset: "BTC/USD",
    amount: 25000,
    status: "LIVE",
  },
  {
    id: "op2",
    trader: {
      id: "trader2",
      name: "Sarah Chen",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    market: "forex",
    type: "SELL",
    asset: "EUR/USD",
    amount: 15000,
    status: "LIVE",
  },
  {
    id: "op3",
    trader: {
      id: "trader3",
      name: "Michael Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    market: "options",
    type: "BUY",
    asset: "AAPL CALL",
    amount: 8500,
    status: "COMPLETED",
  },
  {
    id: "op4",
    trader: {
      id: "trader4",
      name: "David Wilson",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    market: "futures",
    type: "BUY",
    asset: "Gold",
    amount: 12000,
    status: "LIVE",
  },
  {
    id: "op5",
    trader: {
      id: "trader5",
      name: "Emma Roberts",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    market: "stocks",
    type: "SELL",
    asset: "TSLA",
    amount: 18500,
    status: "LIVE",
  },
  {
    id: "op6",
    trader: {
      id: "trader1",
      name: "Alex Morgan",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    market: "crypto",
    type: "SELL",
    asset: "ETH/USD",
    amount: 9500,
    status: "COMPLETED",
  },
  {
    id: "op7",
    trader: {
      id: "trader2",
      name: "Sarah Chen",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 55 * 60000).toISOString(),
    market: "forex",
    type: "BUY",
    asset: "GBP/JPY",
    amount: 7500,
    status: "PENDING",
  },
  {
    id: "op8",
    trader: {
      id: "trader5",
      name: "Emma Roberts",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    timestamp: new Date(Date.now() - 65 * 60000).toISOString(),
    market: "stocks",
    type: "BUY",
    asset: "AMZN",
    amount: 22000,
    status: "LIVE",
  },
]
